spring:
  h2:
    console:
      enabled: true
      path: /db-debug
  application:
    name: ChatServer
  datasource:
    url: jdbc:h2:file:./h2-db
  jpa:
      hibernate:
        ddl-auto: update
server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
      enabled: true
  error:
#    include-stacktrace: never